apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cloud-application
  labels:
    app: Cloud-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Cloud-application
  template:
    metadata:
      labels:
        app: Cloud-application
    spec:
      containers:
      - name: Cloud-application
        image: container-registry.br-se1.magalu.cloud/${MGC_REGISTRY_NAME}/cloud-application-dotnet:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: Cloud-application
spec:
  selector:
    app: Cloud-application
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
