name: Deploy .NET

on:
  workflow_dispatch:

env:
  REGISTRY: container-registry.br-se1.magalu.cloud
  IMAGE_NAME: cloud-application-dotnet
  REGISTRY_USER_NAME: ${{ secrets.MGC_REGISTRY_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Executar testes isolados
      run: dotnet test tests/cloud-application-tests.csproj --no-restore --verbosity normal
      
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login no Container Registry
      run: |
        docker login https://${{ env.REGISTRY }} \
          -u ${{ secrets.MGC_REGISTRY_USER }} \
          -p ${{ secrets.MGC_REGISTRY_PASSWORD }}

    - name: Build e push da imagem
      run: |
        IMAGE=${{ env.REGISTRY }}/${{ secrets.MGC_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Configurar Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.MGC_KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic db-secret \
        --from-literal=url='${{ secrets.DATABASE_URL }}' \
        --dry-run=client -o yaml | kubectl apply -n default -f -

    - name: Deploy no Kubernetes
      run: |
        export MGC_REGISTRY_NAME=${{ secrets.MGC_REGISTRY_NAME }}
        envsubst < k8s/app.yaml | kubectl apply -n default -f -
        kubectl rollout status deployment/cloud-application -n default